--- #YAML:1.0
name:               Hash-Identity
version:            0.01
abstract:           Get a hash that always returns the key
author:
    - Cindy Wang (CindyLinz)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:           0
    Tie::Hash::Identity:  0.01
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
